name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [reopened, opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: openjdk:25
    name: Test JDK 25, ubuntu-latest (container)

    steps:
      - uses: actions/checkout@v5
      - name: Test with Maven
        run: ./mvnw install -B -V -D"maven.javadoc.skip"="true" -P"skipBundlePlugin,minimal-fix-latest" -D"java.util.logging.config.file"="${{github.workspace}}/quickfixj-core/src/test/resources/logging.properties" -D"http.keepAlive"="false" -D"maven.wagon.http.pool"="false" -D"maven.wagon.httpconnectionManager.ttlSeconds"="120"
